// server/api/contests/[id]/pdf/public-program.get.ts
// Public programme of a contest as a PDF (KAN-21): who plays, in what order
// and what they perform, one jornada per page.
//
// The audience's copy, generated by the organisation and handed out by it —
// the gate is the same as the other documents, and nothing here is public.
//
// `works=0` leaves the pieces out. KAN-32 is still open: if the jury ends up
// choosing what is played, a programme with the works printed could not be
// published, and this is what keeps the document usable either way.
import { defineEventHandler, createError, getRouterParam, getQuery } from 'h3'
import { serverSupabaseAdmin, requireOrgOwnerOrMember, internalError } from '~~/server/utils/supabase'
import { createDocument } from '~~/server/utils/pdf/document'
import { pdfFilename, sendPdf } from '~~/server/utils/pdf/response'
import { loadProgramSources } from '~~/server/services/public-program'
import { buildPublicProgram } from '~~/server/utils/pdf/public-program'
import { fill, formatPdfDate, pdfStrings, resolveLocale } from '~~/shared/pdf-i18n'

interface ContestRow {
  name: string
  organizations: { name: string | null; locale: string | null } | null
}

const ISO_DATE = /^\d{4}-\d{2}-\d{2}$/

export default defineEventHandler(async (event) => {
  const contestId = getRouterParam(event, 'id')
  if (!contestId) throw createError({ statusCode: 400, statusMessage: 'Missing contest ID' })

  const query = getQuery(event)
  const date = typeof query.date === 'string' && query.date ? query.date : null
  if (date && !ISO_DATE.test(date)) {
    throw createError({ statusCode: 400, statusMessage: 'invalid_date' })
  }
  const includeWorks = query.works !== '0' && query.works !== 'false'

  const access = await requireOrgOwnerOrMember(event, contestId)
  if (access.member && !['organizer', 'judge'].includes(access.member.role)) {
    throw createError({ statusCode: 403, statusMessage: 'forbidden' })
  }

  const admin = serverSupabaseAdmin()

  const { data, error } = await admin
    .from('contests')
    .select('name, organizations(name, locale)')
    .eq('id', contestId)
    .maybeSingle()
  if (error) throw internalError(event, error, 'contests.select')
  const contest = data as unknown as ContestRow | null
  if (!contest) throw createError({ statusCode: 404, statusMessage: 'Contest not found' })

  let sources
  try {
    sources = await loadProgramSources(admin, contestId)
  } catch (err) {
    throw internalError(event, err, 'round_participants.select')
  }

  const { days, unscheduled } = buildPublicProgram(sources, { includeWorks, date })

  const locale = resolveLocale(contest.organizations?.locale)
  const t = pdfStrings(locale)
  const dayLabel = (value: string) => formatPdfDate(new Date(`${value}T12:00:00Z`), locale)

  const pdf = createDocument({
    title: t.publicProgramTitle,
    contestName: contest.name,
    subtitle: date ? dayLabel(date) : '',
    orgName: contest.organizations?.name ?? null,
    locale,
  })

  // Said once, at the top: someone reading the programme should not have to
  // count to notice that a few turns are still missing.
  if (unscheduled > 0) pdf.note(fill(t.unscheduledNote, { count: unscheduled }))

  const columns = includeWorks
    ? [
        // The work column takes what the others can spare: `table()` draws one
        // line per cell, and a title cut short would lose exactly the catalogue
        // reference this document exists to print.
        { label: t.performanceTime, width: 0.10 },
        { label: t.drawNumber, width: 0.06, align: 'right' as const },
        { label: t.participant, width: 0.23, bold: true },
        { label: t.category, width: 0.16 },
        { label: t.work, width: 0.45 },
      ]
    : [
        { label: t.performanceTime, width: 0.15 },
        { label: t.drawNumber, width: 0.10, align: 'right' as const },
        { label: t.participant, width: 0.42, bold: true },
        { label: t.category, width: 0.33 },
      ]

  if (days.length === 0) {
    pdf.table(columns, [], t.noPerformances)
  }

  days.forEach((day, index) => {
    // A jornada is handed out on its own, so it starts on its own page.
    if (index > 0) pdf.newPage()
    pdf.heading(dayLabel(day.date), `${day.performances} ${t.performances}`)
    pdf.table(
      columns,
      day.rows.map(row => includeWorks
        ? [row.time, row.draw, row.name, row.category, row.work]
        : [row.time, row.draw, row.name, row.category]),
      t.noPerformances,
    )
  })

  return sendPdf(
    event,
    pdf.toBuffer(),
    pdfFilename(t.publicProgramTitle, contest.name, date),
  )
})
